#################################################################
# Dockerfile
#
# Software:         pyVCF
# Software Version: 0.6.8
# Description:      A Variant Call Format reader for Python.
# Website:          https://github.com/jamescasbon/PyVCF
# Base Image:       python:2.7.11
# Run Cmd:          
#################################################################
FROM python:2.7.11

MAINTAINER Adam Struck <strucka@ohsu.edu>

USER root

RUN pip install -U pyVCF

